"""
Janus Optimization Engine (D13) — Rule-Based System Optimization.

Deterministische Regel-Engine für System-Optimierung basierend auf Insights.
Keine KI im Backend-Core. Nur reine Logik mit Schwellenwerten.
"""
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional
from enum import Enum
from pydantic import BaseModel, Field, ConfigDict
import logging

from backend.services.logging.supabase_client import get_supabase_client

logger = logging.getLogger("janus_backend")


class ActionPriority(str, Enum):
    """Priority levels for system actions."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ActionType(str, Enum):
    """Types of system actions."""
    SCALE_UP = "SCALE_UP"
    SCALE_DOWN = "SCALE_DOWN"
    RETRY_CONFIG = "RETRY_CONFIG"
    TIMEOUT_ADJUST = "TIMEOUT_ADJUST"
    CACHE_ENABLE = "CACHE_ENABLE"
    LOAD_BALANCE = "LOAD_BALANCE"
    MODEL_SWITCH = "MODEL_SWITCH"
    MONITOR = "MONITOR"


class SystemAction(BaseModel):
    """System action generated by the Optimization Engine."""
    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(default_factory=lambda: str(__import__('uuid').uuid4()), description="Unique action identifier")
    skill_id: str = Field(..., alias="skill", description="Skill identifier (namespace.action format)")
    model: str = Field(..., description="Model name")
    action_type: ActionType = Field(..., description="Type of action")
    priority: ActionPriority = Field(..., description="Priority level")
    reason: str = Field(..., description="Reason for action")
    current_value: float = Field(..., description="Current metric value")
    threshold: float = Field(..., description="Threshold that triggered action")
    recommendation: str = Field(..., description="Specific recommendation")
    generated_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp of action generation")
    time_window_hours: int = Field(..., description="Time window used for analysis")


class OptimizationEngine:
    """
    Janus Optimization Engine — Rule-Based System Optimization.
    
    Reads logs_insights and generates SystemAction objects based on thresholds:
    - Error Rate > 0.3 → HIGH PRIORITY: SCALE_UP or MODEL_SWITCH
    - Latency > 3000ms → HIGH PRIORITY: TIMEOUT_ADJUST or MODEL_SWITCH
    - Error Rate > 0.5 → CRITICAL: MODEL_SWITCH
    """
    
    def __init__(self, hours: int = 1):
        """
        Initialize Optimization Engine.
        
        Args:
            hours: Time window in hours for insight analysis (default: 1)
        """
        self.hours = hours
        self.supabase = get_supabase_client()
        
        # Thresholds
        self.ERROR_THRESHOLD_HIGH = 0.3
        self.ERROR_THRESHOLD_CRITICAL = 0.5
        self.LATENCY_THRESHOLD_HIGH = 3000  # milliseconds
        self.LATENCY_THRESHOLD_CRITICAL = 5000  # milliseconds
    
    def fetch_insights(self) -> List[Dict[str, Any]]:
        """
        Fetch insights from logs_insights table.
        
        Returns:
            List of insight records
        """
        try:
            cutoff = datetime.utcnow() - timedelta(hours=self.hours)
            
            response = (
                self.supabase
                .table("logs_insights")
                .select("*")
                .gte("generated_at", cutoff.isoformat())
                .execute()
            )
            
            insights = response.data if response.data else []
            return insights
        except Exception as e:
            logger.error(f"[OptimizationEngine] Error fetching insights: {e}", exc_info=True)
            return []
    
    def evaluate_insight(self, insight: Dict[str, Any]) -> Optional[SystemAction]:
        """
        Evaluate a single insight and generate action if thresholds are exceeded.
        
        Args:
            insight: Insight record from logs_insights
        
        Returns:
            SystemAction if threshold exceeded, None otherwise
        """
        skill_id = insight.get("skill", "unknown")
        model = insight.get("model", "unknown")
        error_rate = insight.get("error_rate", 0.0)
        avg_latency_ms = insight.get("avg_latency_ms", 0.0)
        
        # Rule 1: Critical Error Rate (> 0.5)
        if error_rate > self.ERROR_THRESHOLD_CRITICAL:
            return SystemAction(
                skill_id=skill_id,
                model=model,
                action_type=ActionType.MODEL_SWITCH,
                priority=ActionPriority.CRITICAL,
                reason=f"Critical error rate detected ({error_rate:.2%})",
                current_value=error_rate,
                threshold=self.ERROR_THRESHOLD_CRITICAL,
                recommendation=f"[PROVISIONAL] Switch model for {skill_id} immediately. Current model {model} has {error_rate:.2%} error rate.",
                time_window_hours=self.hours
            )
        
        # Rule 2: High Error Rate (> 0.3)
        if error_rate > self.ERROR_THRESHOLD_HIGH:
            return SystemAction(
                skill_id=skill_id,
                model=model,
                action_type=ActionType.SCALE_UP,
                priority=ActionPriority.HIGH,
                reason=f"High error rate detected ({error_rate:.2%})",
                current_value=error_rate,
                threshold=self.ERROR_THRESHOLD_HIGH,
                recommendation=f"[PROVISIONAL] Scale up resources for {skill_id} or consider model switch. Error rate is {error_rate:.2%}.",
                time_window_hours=self.hours
            )
        
        # Rule 3: Critical Latency (> 5000ms)
        if avg_latency_ms > self.LATENCY_THRESHOLD_CRITICAL:
            return SystemAction(
                skill_id=skill_id,
                model=model,
                action_type=ActionType.MODEL_SWITCH,
                priority=ActionPriority.HIGH,
                reason=f"Critical latency detected ({avg_latency_ms:.0f}ms)",
                current_value=avg_latency_ms,
                threshold=self.LATENCY_THRESHOLD_CRITICAL,
                recommendation=f"[PROVISIONAL] Switch model for {skill_id}. Current latency is {avg_latency_ms:.0f}ms.",
                time_window_hours=self.hours
            )
        
        # Rule 4: High Latency (> 3000ms)
        if avg_latency_ms > self.LATENCY_THRESHOLD_HIGH:
            return SystemAction(
                skill_id=skill_id,
                model=model,
                action_type=ActionType.TIMEOUT_ADJUST,
                priority=ActionPriority.HIGH,
                reason=f"High latency detected ({avg_latency_ms:.0f}ms)",
                current_value=avg_latency_ms,
                threshold=self.LATENCY_THRESHOLD_HIGH,
                recommendation=f"[PROVISIONAL] Increase timeout for {skill_id} or switch to faster model. Current latency is {avg_latency_ms:.0f}ms.",
                time_window_hours=self.hours
            )
        
        # Rule 5: Stable System (no action needed)
        if error_rate == 0.0 and avg_latency_ms < 1000:
            return SystemAction(
                skill_id=skill_id,
                model=model,
                action_type=ActionType.MONITOR,
                priority=ActionPriority.LOW,
                reason="System operating normally",
                current_value=error_rate,
                threshold=0.0,
                recommendation=f"[PROVISIONAL] Continue monitoring {skill_id}. System is stable.",
                time_window_hours=self.hours
            )
        
        return None
    
    def store_action(self, action: SystemAction) -> bool:
        """
        Store action in logs_actions table.
        
        Args:
            action: SystemAction to store
        
        Returns:
            True if successful, False otherwise
        """
        try:
            response = (
                self.supabase
                .table("logs_actions")
                .insert(action.model_dump(mode='json', by_alias=True))
                .execute()
            )
            return True
        except Exception as e:
            logger.error(f"[OptimizationEngine] Failed to store action: {e}", exc_info=True)
            return False
    
    def analyze_and_generate_actions(self) -> List[SystemAction]:
        """
        Run full optimization analysis pipeline.
        
        Fetches insights, evaluates each against thresholds,
        generates actions, and stores them.
        
        Returns:
            List of generated SystemAction objects
        """
        insights = self.fetch_insights()
        
        if not insights:
            logger.info("[OptimizationEngine] No insights found for analysis")
            return []
        
        actions = []
        
        for insight in insights:
            action = self.evaluate_insight(insight)
            if action:
                self.store_action(action)
                actions.append(action)
        
        # Sort by priority (CRITICAL > HIGH > MEDIUM > LOW)
        priority_order = {
            ActionPriority.CRITICAL: 0,
            ActionPriority.HIGH: 1,
            ActionPriority.MEDIUM: 2,
            ActionPriority.LOW: 3
        }
        
        actions.sort(key=lambda a: priority_order.get(a.priority, 99))
        
        logger.info(f"[OptimizationEngine] Generated {len(actions)} actions from {len(insights)} insights")
        
        return actions
    
    def generate_decision_report(self, health_matrix: Dict[str, Any]) -> str:
        """
        Generate D13 Decision Report from Health Matrix.
        
        Creates a Markdown report for each degraded skill (< 0.9 pass_rate)
        with the decision block format (Phase 4).
        
        Args:
            health_matrix: Health Matrix from insight_engine.generate_health_matrix()
        
        Returns:
            Markdown-formatted decision report
        """
        matrix = health_matrix.get("matrix", {})
        generated_at = health_matrix.get("generated_at", datetime.utcnow().isoformat())
        
        # Filter degraded skills (< 0.9 pass_rate)
        degraded_skills = {
            skill_id: metrics
            for skill_id, metrics in matrix.items()
            if metrics.get("pass_rate", 1.0) < 0.9
        }
        
        if not degraded_skills:
            return f"""# 🎯 D13 Decision Report

**Generated:** {generated_at}
**Status:** All skills healthy (pass_rate >= 0.9)

No degraded skills detected. No action required.
"""
        
        report_lines = [
            "# 🎯 D13 Decision Report",
            "",
            f"**Generated:** {generated_at}",
            f"**Skills Analyzed:** {len(matrix)}",
            f"**Degraded Skills:** {len(degraded_skills)}",
            ""
        ]
        
        # Generate decision blocks for each degraded skill
        for skill_id, metrics in sorted(degraded_skills.items()):
            pass_rate = metrics.get("pass_rate", 0.0)
            escalation_rate = metrics.get("escalation_rate", 0.0)
            total_runs = metrics.get("total_runs", 0)
            avg_latency = metrics.get("avg_latency_ms", 0.0)
            health_status = metrics.get("health_status", "unknown")
            
            # Determine priority based on pass_rate
            if pass_rate < 0.5:
                priority = "CRITICAL"
                action = "MODEL_SWITCH"
            elif pass_rate < 0.7:
                priority = "HIGH"
                action = "SCALE_UP or MODEL_SWITCH"
            else:
                priority = "MEDIUM"
                action = "MONITOR"
            
            # Generate decision block
            decision_block = f"""## 🚨 {skill_id}

**Health Status:** {health_status.upper()}
**Pass Rate:** {pass_rate:.2%}
**Escalation Rate:** {escalation_rate:.2%}
**Total Runs:** {total_runs}
**Avg Latency:** {avg_latency:.0f}ms

### [PROVISIONAL] Decision Block

**Priority:** {priority}
**Action:** {action}

**Reason:**
- Pass rate is {pass_rate:.2%} (threshold: 0.9)
- Escalation rate is {escalation_rate:.2%}
- System is {health_status}

**Recommendation:**
[PROVISIONAL] Consider {action} for {skill_id}. Current pass rate of {pass_rate:.2%} is below the 0.9 threshold. Investigate root cause and implement corrective action.

---

"""
            report_lines.append(decision_block)
        
        # Summary section
        report_lines.append("## Summary")
        report_lines.append("")
        report_lines.append(f"- **Total Skills Analyzed:** {len(matrix)}")
        report_lines.append(f"- **Healthy Skills:** {len(matrix) - len(degraded_skills)}")
        report_lines.append(f"- **Degraded Skills:** {len(degraded_skills)}")
        report_lines.append("")
        report_lines.append("### Priority Breakdown")
        
        critical_count = sum(1 for m in degraded_skills.values() if m.get("pass_rate", 1.0) < 0.5)
        high_count = sum(1 for m in degraded_skills.values() if 0.5 <= m.get("pass_rate", 1.0) < 0.7)
        medium_count = sum(1 for m in degraded_skills.values() if 0.7 <= m.get("pass_rate", 1.0) < 0.9)
        
        report_lines.append(f"- **CRITICAL:** {critical_count}")
        report_lines.append(f"- **HIGH:** {high_count}")
        report_lines.append(f"- **MEDIUM:** {medium_count}")
        
        return "\n".join(report_lines)
