"""Öffentliche Memory-API (Task 020): CRUD + Retrieval; kompatibel zum früheren memory_manager."""

from .crud_service import (
    GRACE_PERIOD_DAYS,
    _consolidate_memory_after_save,
    _is_storage_path_artifact_fact,
    _merge_existing_memory,
    _serialize_embedding_json,
    archive_old_memories,
    compute_hash,
    prune_expired_memories,
    save_memory_snippet,
    save_raw_memory,
    touch_memory_snippet,
    transfer_facts_to_new_subject,
    update_memory_snippet,
)
from .retrieval_service import (
    _HEALTH_JACCARD_DEDUP_THRESHOLD,
    MAX_CORE_ALWAYS_TOKENS,
    MAX_CORE_QUERY_TOKENS,
    MAX_STM_TOKENS,
    SIMILARITY_THRESHOLD,
    RetrievalContext,
    _dedupe_health_memories_jaccard,
    estimate_tokens,
    find_similar_memory_snippet,
    get_all_facts,
    get_all_memories,
    get_last_subject_from_chat,
    get_memories_for_management,
    retrieve_diamond_context,
    retrieve_diamond_slots,
)

__all__ = [
    # crud_service
    "GRACE_PERIOD_DAYS",
    "_consolidate_memory_after_save",
    "_is_storage_path_artifact_fact",
    "_merge_existing_memory",
    "_serialize_embedding_json",
    "archive_old_memories",
    "compute_hash",
    "prune_expired_memories",
    "save_memory_snippet",
    "save_raw_memory",
    "touch_memory_snippet",
    "transfer_facts_to_new_subject",
    "update_memory_snippet",
    # retrieval_service
    "MAX_CORE_ALWAYS_TOKENS",
    "MAX_CORE_QUERY_TOKENS",
    "MAX_STM_TOKENS",
    "SIMILARITY_THRESHOLD",
    "RetrievalContext",
    "_dedupe_health_memories_jaccard",
    "_HEALTH_JACCARD_DEDUP_THRESHOLD",
    "estimate_tokens",
    "find_similar_memory_snippet",
    "get_all_facts",
    "get_all_memories",
    "get_last_subject_from_chat",
    "get_memories_for_management",
    "retrieve_diamond_context",
    "retrieve_diamond_slots",
]
