[pytest]
pythonpath = .
testpaths = tests
log_cli = true
log_cli_level = INFO

# Enable auto mode for async tests
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

filterwarnings =
    ignore::DeprecationWarning
    ignore::RuntimeWarning
